// <auto-generated />
using System;
using Blanketomat.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blanketomat.DataAccess.Migrations
{
    [DbContext(typeof(BlanketomatContext))]
    partial class BlanketomatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AsistentPredmet", b =>
                {
                    b.Property<int>("AsistentiId")
                        .HasColumnType("int");

                    b.Property<int>("PredmetiId")
                        .HasColumnType("int");

                    b.HasKey("AsistentiId", "PredmetiId");

                    b.HasIndex("PredmetiId");

                    b.ToTable("AsistentPredmet");
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Akreditacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Akreditacije");
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Asistent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SmerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SmerId");

                    b.ToTable("Asistenti");
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Predmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AkreditacijaId")
                        .HasColumnType("int");

                    b.Property<string>("Godina")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SmerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AkreditacijaId");

                    b.HasIndex("SmerId");

                    b.ToTable("Predmeti");
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SmerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SmerId");

                    b.ToTable("Profesori");
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Smer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Smerovi");
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AkreditacijaId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SmerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AkreditacijaId");

                    b.HasIndex("SmerId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("PredmetProfesor", b =>
                {
                    b.Property<int>("PredmetiId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesoriId")
                        .HasColumnType("int");

                    b.HasKey("PredmetiId", "ProfesoriId");

                    b.HasIndex("ProfesoriId");

                    b.ToTable("PredmetProfesor");
                });

            modelBuilder.Entity("PredmetStudent", b =>
                {
                    b.Property<int>("PredmetiId")
                        .HasColumnType("int");

                    b.Property<int>("StudentiId")
                        .HasColumnType("int");

                    b.HasKey("PredmetiId", "StudentiId");

                    b.HasIndex("StudentiId");

                    b.ToTable("PredmetStudent");
                });

            modelBuilder.Entity("AsistentPredmet", b =>
                {
                    b.HasOne("Blanketomat.Domain.Models.Asistent", null)
                        .WithMany()
                        .HasForeignKey("AsistentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blanketomat.Domain.Models.Predmet", null)
                        .WithMany()
                        .HasForeignKey("PredmetiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Asistent", b =>
                {
                    b.HasOne("Blanketomat.Domain.Models.Smer", "Smer")
                        .WithMany("Asistenti")
                        .HasForeignKey("SmerId");

                    b.Navigation("Smer");
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Predmet", b =>
                {
                    b.HasOne("Blanketomat.Domain.Models.Akreditacija", "Akreditacija")
                        .WithMany("Predmeti")
                        .HasForeignKey("AkreditacijaId");

                    b.HasOne("Blanketomat.Domain.Models.Smer", "Smer")
                        .WithMany("Predmeti")
                        .HasForeignKey("SmerId");

                    b.Navigation("Akreditacija");

                    b.Navigation("Smer");
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Profesor", b =>
                {
                    b.HasOne("Blanketomat.Domain.Models.Smer", "Smer")
                        .WithMany("Profesori")
                        .HasForeignKey("SmerId");

                    b.Navigation("Smer");
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Student", b =>
                {
                    b.HasOne("Blanketomat.Domain.Models.Akreditacija", "Akreditacija")
                        .WithMany("Studenti")
                        .HasForeignKey("AkreditacijaId");

                    b.HasOne("Blanketomat.Domain.Models.Smer", "Smer")
                        .WithMany("Studenti")
                        .HasForeignKey("SmerId");

                    b.Navigation("Akreditacija");

                    b.Navigation("Smer");
                });

            modelBuilder.Entity("PredmetProfesor", b =>
                {
                    b.HasOne("Blanketomat.Domain.Models.Predmet", null)
                        .WithMany()
                        .HasForeignKey("PredmetiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blanketomat.Domain.Models.Profesor", null)
                        .WithMany()
                        .HasForeignKey("ProfesoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PredmetStudent", b =>
                {
                    b.HasOne("Blanketomat.Domain.Models.Predmet", null)
                        .WithMany()
                        .HasForeignKey("PredmetiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blanketomat.Domain.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Akreditacija", b =>
                {
                    b.Navigation("Predmeti");

                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("Blanketomat.Domain.Models.Smer", b =>
                {
                    b.Navigation("Asistenti");

                    b.Navigation("Predmeti");

                    b.Navigation("Profesori");

                    b.Navigation("Studenti");
                });
#pragma warning restore 612, 618
        }
    }
}
